window.DLA_ACTS = [
  {
    id: "utopia",
    name: "Utopia",
    eyebrow: "Campo latente",
    statement:
      "Antes da forma fixa, a mesa existe como horizonte. A agregacao ainda nao cristalizou, mas o campo ja irradia futuros possiveis.",
    application:
      "Indicado para mesa vazia, pre-entrada ou baixa ocupacao. O sistema trabalha antecipacao, respiracao, halo e possibilidade.",
    palette: {
      bg: "#f6f1e9",
      glow: "#ffe98d",
      primary: "#ff5a36",
      secondary: "#3a66cf",
      tertiary: "#8ee6ff",
      line: "#17202d",
      seed: "#fff8d1",
    },
    behavior: {
      seedPattern: "ring",
      baseSeeds: 2,
      walkers: 90,
      maxNodes: 480,
      stickDistance: 11,
      stickyChance: 0.07,
      stepSize: 2.9,
      turnRate: 0.92,
      orbit: 0.020,
      inwardPull: 0.010,
      childScale: 0.994,
      nodeSize: 2.9,
      bridgeDistance: 88,
      bridgeChance: 0.04,
      lineAlpha: 0.14,
      trailFade: 0.082,
      bloom: 0.90,
      shape: "orb",
      geometry: "rings",
      showWalkers: true,
    },
    variableNotes: [
      "Baixa adesao para deixar o meio aberto e luminoso.",
      "Poucas sementes sugerem potencia, nao saturacao.",
      "A cor alterna entre solar, azul e iridescencia.",
    ],
  },
  {
    id: "individuo",
    name: "Individuo",
    eyebrow: "Nucleacao",
    statement:
      "A forma nasce de um nucleo singular. Cada chegada condensa um centro e transforma tensao em cristalizacao.",
    application:
      "Indicado para 1 ou 2 pratos com permanencia alta. O visual trabalha foco, presenca, coluna central e detalhamento mineral.",
    palette: {
      bg: "#f2ece3",
      glow: "#ffbf55",
      primary: "#d9911f",
      secondary: "#6a4418",
      tertiary: "#fce7bb",
      line: "#21170f",
      seed: "#fff4dc",
    },
    behavior: {
      seedPattern: "single",
      baseSeeds: 1,
      walkers: 112,
      maxNodes: 560,
      stickDistance: 12,
      stickyChance: 0.19,
      stepSize: 2.2,
      turnRate: 0.56,
      orbit: 0.006,
      inwardPull: 0.030,
      childScale: 0.989,
      nodeSize: 3.4,
      bridgeDistance: 70,
      bridgeChance: 0.03,
      lineAlpha: 0.22,
      trailFade: 0.070,
      bloom: 0.55,
      shape: "diamond",
      geometry: "spine",
      showWalkers: false,
    },
    variableNotes: [
      "Adesao alta para cristalizar rapido ao redor de um centro.",
      "Escala dos filhos diminui por geracao para reforcar mineralidade.",
      "A paleta privilegia ambar, ouro e sombra quente.",
    ],
  },
  {
    id: "redes",
    name: "Redes",
    eyebrow: "Coexistencia",
    statement:
      "A forma deixa de pertencer a uma unica origem e passa a emergir da relacao entre varios polos ativos.",
    application:
      "Indicado para 3 ou 4 pratos coexistindo com estabilidade media ou alta. O visual privilegia pontes, malhas e transferencia.",
    palette: {
      bg: "#eef3f8",
      glow: "#99bfff",
      primary: "#2350be",
      secondary: "#6c92f1",
      tertiary: "#edf5ff",
      line: "#102140",
      seed: "#ffffff",
    },
    behavior: {
      seedPattern: "line",
      baseSeeds: 3,
      walkers: 128,
      maxNodes: 700,
      stickDistance: 13,
      stickyChance: 0.14,
      stepSize: 2.5,
      turnRate: 0.70,
      orbit: 0.010,
      inwardPull: 0.020,
      childScale: 0.992,
      nodeSize: 3.0,
      bridgeDistance: 128,
      bridgeChance: 0.18,
      lineAlpha: 0.28,
      trailFade: 0.074,
      bloom: 0.62,
      shape: "square",
      geometry: "grid",
      showWalkers: true,
    },
    variableNotes: [
      "Distancia de ponte maior para favorecer malhas entre linhagens.",
      "Mais sementes para espalhar centros de propagacao.",
      "Azuis frios e branco ativam leitura de rede e tecnologia sensivel.",
    ],
  },
  {
    id: "enxame",
    name: "Enxame",
    eyebrow: "Troca viva",
    statement:
      "A inteligencia emerge do atrito entre agentes. A mesa nao fixa um desenho unico, ela oscila, troca, corrige e recombina.",
    application:
      "Indicado para 4 a 6 pratos com alta troca, aproximacao e retirada frequentes. O visual libera swarm, pulsos e turbulencia.",
    palette: {
      bg: "#120f12",
      glow: "#ff6a4c",
      primary: "#f0442f",
      secondary: "#8a2d20",
      tertiary: "#f6bc75",
      line: "#f4d8b6",
      seed: "#fff4e2",
    },
    behavior: {
      seedPattern: "swarm",
      baseSeeds: 5,
      walkers: 182,
      maxNodes: 640,
      stickDistance: 10,
      stickyChance: 0.09,
      stepSize: 3.5,
      turnRate: 1.28,
      orbit: 0.030,
      inwardPull: 0.008,
      childScale: 0.996,
      nodeSize: 2.5,
      bridgeDistance: 104,
      bridgeChance: 0.09,
      lineAlpha: 0.12,
      trailFade: 0.110,
      bloom: 0.86,
      shape: "shard",
      geometry: "burst",
      showWalkers: true,
    },
    variableNotes: [
      "Turn rate alto para deslocar o sistema do cristal para o fluxo.",
      "Mais walkers mantem materia viva circulando em torno das sementes.",
      "Vermelhos, cobre e calor reforcam corpo, friccao e movimento.",
    ],
  },
  {
    id: "poiesis",
    name: "Poiesis",
    eyebrow: "Autocriacao",
    statement:
      "O sistema ja nao ilustra apenas uma acao presente. Ele parece produzir continuidade, memoria e renascimento por conta propria.",
    application:
      "Indicado para padroes recorrentes entre mesas, permanencia longa e ecos entre combinacoes. O visual trabalha regeneracao e memoria.",
    palette: {
      bg: "#f3eee7",
      glow: "#d7ac74",
      primary: "#9d6430",
      secondary: "#3d6f67",
      tertiary: "#f4e5cb",
      line: "#2a211a",
      seed: "#fff8ef",
    },
    behavior: {
      seedPattern: "spiral",
      baseSeeds: 3,
      walkers: 136,
      maxNodes: 760,
      stickDistance: 12,
      stickyChance: 0.16,
      stepSize: 2.7,
      turnRate: 0.78,
      orbit: 0.014,
      inwardPull: 0.024,
      childScale: 0.991,
      nodeSize: 3.2,
      bridgeDistance: 118,
      bridgeChance: 0.14,
      lineAlpha: 0.24,
      trailFade: 0.078,
      bloom: 0.72,
      shape: "petal",
      geometry: "petals",
      showWalkers: true,
    },
    variableNotes: [
      "Memoria de linhagem e pontes tardias para sensacao de regeneracao.",
      "Mistura de cobre, pergaminho e verde profundo para vida tecno-organica.",
      "Ato ideal para conexoes entre mesas e retorno de padroes ao longo do tempo.",
    ],
  },
];
