window.MESA_ACTS = [
  {
    id: "utopia",
    name: "Utopia",
    eyebrow: "Campo espectral",
    statement:
      "Luz branca antes da forma fixa. O campo responde como um halo iridescente, com atraso RGB e materia ainda em suspensao.",
    application:
      "Bom para baixa ocupacao, pre-entrada e estado de promessa. O sistema privilegia atraso cromatico, neblina branca e orbitas suaves.",
    effect: "rgb-delay",
    palette: {
      bgStart: "#f8f8ff",
      bgEnd: "#efe5ff",
      primary: "#ffffff",
      secondary: "#ff5ec7",
      tertiary: "#49d7ff",
      glow: "#ffffff",
      spark: "#7f6cff",
      baseTint: "#191a22",
      level1: "#f4ebff",
      level2: "#d5c5ff",
      level3: "#b6efff",
      mesa: "#ffffff",
      plate: "#fefaff",
      top: "#ffffff",
      line: "#d7d2ff",
    },
  },
  {
    id: "individuo",
    name: "Individuo",
    eyebrow: "Nucleacao mineral",
    statement:
      "Cada prato concentra materia e deixa o sistema cristalizar ao redor de um nucleo. A leitura fica quente, precisa e concentrada.",
    application:
      "Bom para poucos pratos com alta permanencia. O visual privilegia coluna, ambar, ouro palido e estruturacao por densidade.",
    effect: "warm-core",
    palette: {
      bgStart: "#f5efe4",
      bgEnd: "#ebe2d1",
      primary: "#f2c463",
      secondary: "#d59a1a",
      tertiary: "#f6ead0",
      glow: "#fff4d8",
      spark: "#b46b12",
      baseTint: "#211910",
      level1: "#f0d58d",
      level2: "#e2be64",
      level3: "#f7efe0",
      mesa: "#fff5db",
      plate: "#fff1c8",
      top: "#fff8e8",
      line: "#efd6a2",
    },
  },
  {
    id: "redes",
    name: "Redes",
    eyebrow: "Transferencia liquida",
    statement:
      "As mesas deixam de operar como ilhas e passam a trocar materia. O visual privilegia conexao, agua clara e continuidade entre polos.",
    application:
      "Bom para coexistencia mais estavel entre mesas. O sistema reforca pontes, filamentos, transferencia e campos frios.",
    effect: "network-flow",
    palette: {
      bgStart: "#eef9fb",
      bgEnd: "#dff1f4",
      primary: "#7ef4e6",
      secondary: "#57cde8",
      tertiary: "#f3ffff",
      glow: "#d4fffb",
      spark: "#5a8fff",
      baseTint: "#102028",
      level1: "#bcfff6",
      level2: "#83efe3",
      level3: "#b6f7ff",
      mesa: "#f6ffff",
      plate: "#dffefd",
      top: "#f3ffff",
      line: "#8cecf8",
    },
  },
  {
    id: "enxame",
    name: "Enxame",
    eyebrow: "Atrito vital",
    statement:
      "A materia perde repouso e entra em troca constante. O campo fica acido, vivo e responsivo ao movimento coletivo.",
    application:
      "Bom para ocupacao alta e troca frequente. O sistema reforca pulsos verdes, vetores curtos, swarm e agitacao local.",
    effect: "acid-swarm",
    palette: {
      bgStart: "#edf5de",
      bgEnd: "#d5efc7",
      primary: "#99ff47",
      secondary: "#57db54",
      tertiary: "#f8fff2",
      glow: "#e6ffd2",
      spark: "#35c85d",
      baseTint: "#132012",
      level1: "#c7ff8e",
      level2: "#98ff58",
      level3: "#d5ffc0",
      mesa: "#f6ffe9",
      plate: "#eeffd6",
      top: "#fcfff8",
      line: "#90f57f",
    },
  },
  {
    id: "poiesis",
    name: "Poiesis",
    eyebrow: "Retorno de memoria",
    statement:
      "O sistema passa a parecer autocriado. A cor retorna ao espectro, mas com mais memoria, mais gravidade e mais recorrencia.",
    application:
      "Bom para ecos entre mesas, recorrencia e fechamento do ciclo. O visual privilegia retorno cromatico, reconexao e permanencia sensivel.",
    effect: "memory-return",
    palette: {
      bgStart: "#f7f4fb",
      bgEnd: "#ece6f8",
      primary: "#6e63ff",
      secondary: "#ef5ab8",
      tertiary: "#f8f3ff",
      glow: "#ffffff",
      spark: "#53d4ff",
      baseTint: "#1b1423",
      level1: "#d7cef9",
      level2: "#b095ff",
      level3: "#f0b0d7",
      mesa: "#fffaff",
      plate: "#f8efff",
      top: "#ffffff",
      line: "#d5c4ff",
    },
  },
];
